export enum LoanStatus {
    REQUESTED = 'REQUESTED',
    REJECTED = 'REJECTED',
    LISTED = 'LISTED',
    ACTIVE = 'ACTIVE',
    PAID = 'PAID',
    CANCELED = 'CANCELED',
    DEFAULTED = 'DEFAULTED'
}